### PR TITLE
Fixing compliance issues

### LINKED ISSUE #6: Compliance issues
- [x] Karamba3d_Toolkit\.ci\unit-tests\Karamba3D_Engine_Tests\CustomAsserts.cs
Line: 45
Files cannot contain more than one class - For more information see https://bhom.xyz/documentation/DevOps/Code%20Compliance%20and%20CI/Compliance%20Checks/HasSingleClass

 - [x] Karamba3d_Toolkit\.ci\unit-tests\Karamba3D_Engine_Tests\CustomAsserts.cs
Line: 36
Invalid oM property: Object properties must be virtual - For more information see https://bhom.xyz/documentation/DevOps/Code%20Compliance%20and%20CI/Compliance%20Checks/IsVirtualProperty

 - [x] Karamba3d_Toolkit\.ci\unit-tests\Karamba3D_Engine_Tests\CustomAsserts.cs
Line: 37
Invalid oM property: Object properties must be virtual - For more information see https://bhom.xyz/documentation/DevOps/Code%20Compliance%20and%20CI/Compliance%20Checks/IsVirtualProperty

 - [x] Karamba3d_Toolkit\.ci\unit-tests\Karamba3D_Engine_Tests\CustomAsserts.cs
Line: 39
Invalid oM property: Object properties must be virtual - For more information see https://bhom.xyz/documentation/DevOps/Code%20Compliance%20and%20CI/Compliance%20Checks/IsVirtualProperty

 - [x] Karamba3d_Toolkit\.ci\unit-tests\Karamba3D_Engine_Tests\CustomAsserts.cs
Line: 40
Invalid oM property: Object properties must be virtual - For more information see https://bhom.xyz/documentation/DevOps/Code%20Compliance%20and%20CI/Compliance%20Checks/IsVirtualProperty

 - [x] Karamba3d_Toolkit\.ci\unit-tests\Karamba3D_Engine_Tests\CustomAsserts.cs
Line: 42
Invalid oM property: Object properties must be virtual - For more information see https://bhom.xyz/documentation/DevOps/Code%20Compliance%20and%20CI/Compliance%20Checks/IsVirtualProperty

 - [x] Karamba3d_Toolkit\.ci\unit-tests\Karamba3D_Engine_Tests\CustomAsserts.cs
Line: 34
Class (object) name must match file name - For more information see https://bhom.xyz/documentation/DevOps/Code%20Compliance%20and%20CI/Compliance%20Checks/ObjectNameMatchesFileName

 - [x] Karamba3d_Toolkit\.ci\unit-tests\Karamba3D_Engine_Tests\CustomAsserts.cs
Line: 42
Invalid oM property: Object properties must have a public getter - For more information see https://bhom.xyz/documentation/DevOps/Code%20Compliance%20and%20CI/Compliance%20Checks/HasPublicGet

 - [x] Karamba3d_Toolkit\Karamba3D_Engine\Resource.Designer.cs
Line: 25
Incorrect Engine class name based on file path - For more information see https://bhom.xyz/documentation/DevOps/Code%20Compliance%20and%20CI/Compliance%20Checks/EngineClassMatchesFilePath

 - [x] Karamba3d_Toolkit\Karamba3D_Engine\Resource.Designer.cs
Line: 25
Invalid Engine class: Engine classes must be static - For more information see https://bhom.xyz/documentation/DevOps/Code%20Compliance%20and%20CI/Compliance%20Checks/IsStaticClass

 - [x] Karamba3d_Toolkit\Karamba3D_Engine\Resource.Designer.cs
Line: 25
Invalid Engine class name - For more information see https://bhom.xyz/documentation/DevOps/Code%20Compliance%20and%20CI/Compliance%20Checks/IsValidEngineClassName

 - [x] Karamba3d_Toolkit\Karamba3D_ToolkitTests\CustomAsserts.cs
Line: 45
Files cannot contain more than one class - For more information see https://bhom.xyz/documentation/DevOps/Code%20Compliance%20and%20CI/Compliance%20Checks/HasSingleClass

 - [x] Karamba3d_Toolkit\Karamba3D_ToolkitTests\CustomAsserts.cs
Line: 36
Invalid oM property: Object properties must be virtual - For more information see https://bhom.xyz/documentation/DevOps/Code%20Compliance%20and%20CI/Compliance%20Checks/IsVirtualProperty

 - [x] Karamba3d_Toolkit\Karamba3D_ToolkitTests\CustomAsserts.cs
Line: 37
Invalid oM property: Object properties must be virtual - For more information see https://bhom.xyz/documentation/DevOps/Code%20Compliance%20and%20CI/Compliance%20Checks/IsVirtualProperty

 - [x] Karamba3d_Toolkit\Karamba3D_ToolkitTests\CustomAsserts.cs
Line: 39
Invalid oM property: Object properties must be virtual - For more information see https://bhom.xyz/documentation/DevOps/Code%20Compliance%20and%20CI/Compliance%20Checks/IsVirtualProperty

 - [x] Karamba3d_Toolkit\Karamba3D_ToolkitTests\CustomAsserts.cs
Line: 40
Invalid oM property: Object properties must be virtual - For more information see https://bhom.xyz/documentation/DevOps/Code%20Compliance%20and%20CI/Compliance%20Checks/IsVirtualProperty

 - [x] Karamba3d_Toolkit\Karamba3D_ToolkitTests\CustomAsserts.cs
Line: 42
Invalid oM property: Object properties must be virtual - For more information see https://bhom.xyz/documentation/DevOps/Code%20Compliance%20and%20CI/Compliance%20Checks/IsVirtualProperty

 - [x] Karamba3d_Toolkit\Karamba3D_ToolkitTests\CustomAsserts.cs
Line: 34
Class (object) name must match file name - For more information see https://bhom.xyz/documentation/DevOps/Code%20Compliance%20and%20CI/Compliance%20Checks/ObjectNameMatchesFileName

 - [x] Karamba3d_Toolkit\Karamba3D_ToolkitTests\CustomAsserts.cs
Line: 42
Invalid oM property: Object properties must have a public getter - For more information see https://bhom.xyz/documentation/DevOps/Code%20Compliance%20and%20CI/Compliance%20Checks/HasPublicGet

 - [x] Karamba3d_Toolkit\Karamba3D_Engine\Resource.Designer.cs
Line: 1
Copyright message is invalid - For more information see https://bhom.xyz/documentation/DevOps/Code%20Compliance%20and%20CI/Compliance%20Checks/HasValidCopyright

 - [x] Karamba3d_Toolkit\Karamba3D_Engine\Convert\ToBHoM\_IToBHoM.cs
Line: 1
Copyright message is invalid - For more information see https://bhom.xyz/documentation/DevOps/Code%20Compliance%20and%20CI/Compliance%20Checks/HasValidCopyright

 - [x] Karamba3d_Toolkit\Karamba3D_Engine\Objects\MessageLevel.cs
Line: 1
Copyright message is invalid - For more information see https://bhom.xyz/documentation/DevOps/Code%20Compliance%20and%20CI/Compliance%20Checks/HasValidCopyright

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes #6

### Test files

See Test project in the `.ci` folder, and test scripts attached to https://github.com/BHoM/Karamba3D_Toolkit/pull/4.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
Please resolve the copyright compliance issue for the file listed and then this should be good to go 😄

**Comment by alelom** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Review by FraserGreenroyd — APPROVED** [review]
This looks good now on code review and bot review, thanks @alelom

**Pull request merged**
