### PR TITLE
Fixes to project compliance

### LINKED ISSUE #14: Fix project compliance
Per output [here](https://github.com/BHoM/Karamba3D_Toolkit/pull/13/checks?check_run_id=17107534561).

### PR DESCRIPTION
**Pull request by albinber**
### Issues addressed by this PR

Closes #14

### CODE REVIEW

**Comment by albinber** [comment]
@bhombot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core, serialisation, null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check serialisation
@BHoMBot check null-handling

**Review by FraserGreenroyd — APPROVED** [review]
Updates make sense, compliance checks are happy, good to go.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: ready-to-merge

**Pull request merged**
